/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.3
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2019 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* Pin_1 */
#define Pin_1_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define Pin_1_0_INBUF_ENABLED 1u
#define Pin_1_0_INIT_DRIVESTATE 0u
#define Pin_1_0_INIT_MUXSEL 18u
#define Pin_1_0_INPUT_SYNC 2u
#define Pin_1_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_1_0_NUM 0u
#define Pin_1_0_PORT GPIO_PRT5
#define Pin_1_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_1_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Pin_1_DRIVEMODE CY_GPIO_DM_HIGHZ
#define Pin_1_INBUF_ENABLED 1u
#define Pin_1_INIT_DRIVESTATE 0u
#define Pin_1_INIT_MUXSEL 18u
#define Pin_1_INPUT_SYNC 2u
#define Pin_1_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_1_NUM 0u
#define Pin_1_PORT GPIO_PRT5
#define Pin_1_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_1_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Pin_2 */
#define Pin_2_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Pin_2_0_INBUF_ENABLED 0u
#define Pin_2_0_INIT_DRIVESTATE 1u
#define Pin_2_0_INIT_MUXSEL 18u
#define Pin_2_0_INPUT_SYNC 2u
#define Pin_2_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_2_0_NUM 1u
#define Pin_2_0_PORT GPIO_PRT5
#define Pin_2_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_2_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Pin_2_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Pin_2_INBUF_ENABLED 0u
#define Pin_2_INIT_DRIVESTATE 1u
#define Pin_2_INIT_MUXSEL 18u
#define Pin_2_INPUT_SYNC 2u
#define Pin_2_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_2_NUM 1u
#define Pin_2_PORT GPIO_PRT5
#define Pin_2_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_2_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* FLASHINFO */
#define FLASHINFO_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define FLASHINFO_0_INBUF_ENABLED 1u
#define FLASHINFO_0_INIT_DRIVESTATE 0u
#define FLASHINFO_0_INIT_MUXSEL 0u
#define FLASHINFO_0_INPUT_SYNC 2u
#define FLASHINFO_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define FLASHINFO_0_NUM 0u
#define FLASHINFO_0_PORT GPIO_PRT0
#define FLASHINFO_0_SLEWRATE CY_GPIO_SLEW_FAST
#define FLASHINFO_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define FLASHINFO_DRIVEMODE CY_GPIO_DM_HIGHZ
#define FLASHINFO_INBUF_ENABLED 1u
#define FLASHINFO_INIT_DRIVESTATE 0u
#define FLASHINFO_INIT_MUXSEL 0u
#define FLASHINFO_INPUT_SYNC 2u
#define FLASHINFO_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define FLASHINFO_NUM 0u
#define FLASHINFO_PORT GPIO_PRT0
#define FLASHINFO_SLEWRATE CY_GPIO_SLEW_FAST
#define FLASHINFO_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* FLASHWRITE */
#define FLASHWRITE_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define FLASHWRITE_0_INBUF_ENABLED 0u
#define FLASHWRITE_0_INIT_DRIVESTATE 0u
#define FLASHWRITE_0_INIT_MUXSEL 0u
#define FLASHWRITE_0_INPUT_SYNC 2u
#define FLASHWRITE_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define FLASHWRITE_0_NUM 1u
#define FLASHWRITE_0_PORT GPIO_PRT0
#define FLASHWRITE_0_SLEWRATE CY_GPIO_SLEW_FAST
#define FLASHWRITE_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define FLASHWRITE_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define FLASHWRITE_INBUF_ENABLED 0u
#define FLASHWRITE_INIT_DRIVESTATE 0u
#define FLASHWRITE_INIT_MUXSEL 0u
#define FLASHWRITE_INPUT_SYNC 2u
#define FLASHWRITE_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define FLASHWRITE_NUM 1u
#define FLASHWRITE_PORT GPIO_PRT0
#define FLASHWRITE_SLEWRATE CY_GPIO_SLEW_FAST
#define FLASHWRITE_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* LedDriverSdaOut */
#define LedDriverSdaOut_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LedDriverSdaOut_0_INBUF_ENABLED 0u
#define LedDriverSdaOut_0_INIT_DRIVESTATE 0u
#define LedDriverSdaOut_0_INIT_MUXSEL 0u
#define LedDriverSdaOut_0_INPUT_SYNC 2u
#define LedDriverSdaOut_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LedDriverSdaOut_0_NUM 4u
#define LedDriverSdaOut_0_PORT GPIO_PRT0
#define LedDriverSdaOut_0_SLEWRATE CY_GPIO_SLEW_FAST
#define LedDriverSdaOut_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define LedDriverSdaOut_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LedDriverSdaOut_INBUF_ENABLED 0u
#define LedDriverSdaOut_INIT_DRIVESTATE 0u
#define LedDriverSdaOut_INIT_MUXSEL 0u
#define LedDriverSdaOut_INPUT_SYNC 2u
#define LedDriverSdaOut_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LedDriverSdaOut_NUM 4u
#define LedDriverSdaOut_PORT GPIO_PRT0
#define LedDriverSdaOut_SLEWRATE CY_GPIO_SLEW_FAST
#define LedDriverSdaOut_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* LedDriverClockPin */
#define LedDriverClockPin_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LedDriverClockPin_0_INBUF_ENABLED 0u
#define LedDriverClockPin_0_INIT_DRIVESTATE 1u
#define LedDriverClockPin_0_INIT_MUXSEL 8u
#define LedDriverClockPin_0_INPUT_SYNC 2u
#define LedDriverClockPin_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LedDriverClockPin_0_NUM 4u
#define LedDriverClockPin_0_PORT GPIO_PRT9
#define LedDriverClockPin_0_SLEWRATE CY_GPIO_SLEW_FAST
#define LedDriverClockPin_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define LedDriverClockPin_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LedDriverClockPin_INBUF_ENABLED 0u
#define LedDriverClockPin_INIT_DRIVESTATE 1u
#define LedDriverClockPin_INIT_MUXSEL 8u
#define LedDriverClockPin_INPUT_SYNC 2u
#define LedDriverClockPin_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LedDriverClockPin_NUM 4u
#define LedDriverClockPin_PORT GPIO_PRT9
#define LedDriverClockPin_SLEWRATE CY_GPIO_SLEW_FAST
#define LedDriverClockPin_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* LedDriverLatchOut */
#define LedDriverLatchOut_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LedDriverLatchOut_0_INBUF_ENABLED 0u
#define LedDriverLatchOut_0_INIT_DRIVESTATE 0u
#define LedDriverLatchOut_0_INIT_MUXSEL 0u
#define LedDriverLatchOut_0_INPUT_SYNC 2u
#define LedDriverLatchOut_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LedDriverLatchOut_0_NUM 1u
#define LedDriverLatchOut_0_PORT GPIO_PRT9
#define LedDriverLatchOut_0_SLEWRATE CY_GPIO_SLEW_FAST
#define LedDriverLatchOut_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define LedDriverLatchOut_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LedDriverLatchOut_INBUF_ENABLED 0u
#define LedDriverLatchOut_INIT_DRIVESTATE 0u
#define LedDriverLatchOut_INIT_MUXSEL 0u
#define LedDriverLatchOut_INPUT_SYNC 2u
#define LedDriverLatchOut_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LedDriverLatchOut_NUM 1u
#define LedDriverLatchOut_PORT GPIO_PRT9
#define LedDriverLatchOut_SLEWRATE CY_GPIO_SLEW_FAST
#define LedDriverLatchOut_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* LedDriverClockComOut */
#define LedDriverClockComOut_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LedDriverClockComOut_0_INBUF_ENABLED 0u
#define LedDriverClockComOut_0_INIT_DRIVESTATE 1u
#define LedDriverClockComOut_0_INIT_MUXSEL 8u
#define LedDriverClockComOut_0_INPUT_SYNC 2u
#define LedDriverClockComOut_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LedDriverClockComOut_0_NUM 2u
#define LedDriverClockComOut_0_PORT GPIO_PRT9
#define LedDriverClockComOut_0_SLEWRATE CY_GPIO_SLEW_FAST
#define LedDriverClockComOut_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define LedDriverClockComOut_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LedDriverClockComOut_INBUF_ENABLED 0u
#define LedDriverClockComOut_INIT_DRIVESTATE 1u
#define LedDriverClockComOut_INIT_MUXSEL 8u
#define LedDriverClockComOut_INPUT_SYNC 2u
#define LedDriverClockComOut_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LedDriverClockComOut_NUM 2u
#define LedDriverClockComOut_PORT GPIO_PRT9
#define LedDriverClockComOut_SLEWRATE CY_GPIO_SLEW_FAST
#define LedDriverClockComOut_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
