/*******************************************************************************
* File Name: cyfitter_sysint.h
* 
* PSoC Creator  4.3
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2019 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_H
#define INCLUDED_CYFITTER_SYSINT_H
#include "cy_device_headers.h"

/* dataIsr */
#define dataIsr__INTC_CORTEXM4_ASSIGNED 1
#define dataIsr__INTC_CORTEXM4_PRIORITY 7u
#define dataIsr__INTC_NUMBER 122u
#define dataIsr_INTC_CORTEXM4_ASSIGNED 1
#define dataIsr_INTC_CORTEXM4_PRIORITY 7u
#define dataIsr_INTC_NUMBER 122u

/* Timer_ISR */
#define Timer_ISR__INTC_CORTEXM4_ASSIGNED 1
#define Timer_ISR__INTC_CORTEXM4_PRIORITY 7u
#define Timer_ISR__INTC_NUMBER 90u
#define Timer_ISR_INTC_CORTEXM4_ASSIGNED 1
#define Timer_ISR_INTC_CORTEXM4_PRIORITY 7u
#define Timer_ISR_INTC_NUMBER 90u

/* DBG_SCB_IRQ */
#define DBG_SCB_IRQ__INTC_CORTEXM0P_ASSIGNED 1
#define DBG_SCB_IRQ__INTC_CORTEXM0P_MUX 9u
#define DBG_SCB_IRQ__INTC_CORTEXM0P_PRIORITY 3u
#define DBG_SCB_IRQ__INTC_NUMBER 46u
#define DBG_SCB_IRQ_INTC_CORTEXM0P_ASSIGNED 1
#define DBG_SCB_IRQ_INTC_CORTEXM0P_MUX 9u
#define DBG_SCB_IRQ_INTC_CORTEXM0P_PRIORITY 3u
#define DBG_SCB_IRQ_INTC_NUMBER 46u

/* BLE_bless_isr */
#define BLE_bless_isr__INTC_CORTEXM4_ASSIGNED 1
#define BLE_bless_isr__INTC_CORTEXM4_PRIORITY 7u
#define BLE_bless_isr__INTC_NUMBER 24u
#define BLE_bless_isr_INTC_CORTEXM4_ASSIGNED 1
#define BLE_bless_isr_INTC_CORTEXM4_PRIORITY 7u
#define BLE_bless_isr_INTC_NUMBER 24u

#endif /* INCLUDED_CYFITTER_SYSINT_H */
